name: Deploy via FTP (Debug)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Secret Availability
        run: |
          if [ -n "${{ secrets.FTP_SERVER }}" ]; then
            echo "FTP_SERVER secret is available"
          else
            echo "FTP_SERVER secret is NOT available"
          fi
          if [ -n "${{ secrets.FTP_USERNAME }}" ]; then
            echo "FTP_USERNAME secret is available"
          else
            echo "FTP_USERNAME secret is NOT available"
          fi
          if [ -n "${{ secrets.FTP_PASSWORD }}" ]; then
            echo "FTP_PASSWORD secret is available"
          else
            echo "FTP_PASSWORD secret is NOT available"
          fi
      
      - name: Deploy to InMotion Hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "/public_html/"
          local-dir: "./"